id: open-question-analytics-impact
learningObjectives:
  - Reflect on how analytics can improve product decisions.
hints:
  - Think about how tracking user actions can reveal pain points or
    opportunities for improvement. For inspiration, check out [Segment's guide
    to Customer Data Platforms](https://segment.com/resources/cdp/).
  - Consider how analytics can help prioritize features, fix bugs faster, or
    personalize the user experience.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: >-
              Alright, you've made it almost to the end of our Segment
              integration quest! Before we wrap up, let's take a step back and
              think about the bigger picture. Why do we even bother with all
              this event tracking and analytics setup? (Besides making Ness
              happy, of course.)

              Analytics tools like Segment aren't just for collecting vanity metrics or making dashboards look pretty. They're about understanding how real people use your product--what's working, what's confusing, and where users drop off. This data can drive everything from bug fixes to major product pivots.

              For example, imagine you notice that users are creating accounts but rarely listing items for sale. With event tracking in place, you can dig into the user journey, spot where engagement drops, and experiment with changes--maybe a better onboarding flow or a new call-to-action. Without analytics, you're basically flying blind.

              So here's my question for you:

              How can having detailed analytics and event tracking (like what you just set up with Segment) help a product team make better decisions for both the business and the user experience?

              Share your thoughts--there's no single right answer, but try to connect it to what we've covered in this quest.
trigger:
  type: user_message
  params:
    person: lucca
  flowNode:
    do:
      - actionId: parse_user_response
        name: user_answer
        params:
          prompt: "

            \    Please evaluate the user's answer in relation to
            the expected answer: Having detailed analytics and event tracking
            allows a product team to see exactly how users interact with the
            app. This helps identify which features are popular, where users get
            stuck, and what actions lead to conversions or drop-offs. With this
            data, the team can make informed decisions--like improving confusing
            flows, prioritizing high-impact features, or fixing bugs that affect
            many users. Ultimately, analytics help create a better user
            experience and drive business growth by focusing efforts where they
            matter most..

            \    # Assessment Criteria

            \    - Determine if the user's response demonstrates a
            clear understanding of the key concepts and ideas presented in the
            expected answer.

            \    - Consider synonyms, paraphrasing, and different
            phrasing that convey the same meaning.

            \    - Be flexible and focus on the essence of the
            answer rather than exact wording.

            \ \ 

            \    # Response Guidelines:

            \    - If the user's answer is correct or shows
            sufficient understanding, return 'correct: true'.

            \      - Provide a positive and affirming message,
            congratulating them and reinforcing their understanding.

            \    - If the user's answer is incorrect or incomplete,
            return 'correct: false'.

            \      - Gently explain why the answer is not fully
            correct or what may be missing.

            \      - Encourage them to try again, being empathetic
            and supportive.

            \ \ 

            \    # Tone and Style:

            \    - Use friendly and encouraging language.

            \    - Be empathetic to the user's learning process.

            \    - Focus on helping the user learn and understand
            the material.

            \  "
          schema:
            correct: boolean
            reply: string
    if:
      conditions:
        - conditionId: is_truthy
          params:
            value: ${outputs.user_answer.value.correct}
      then:
        do:
          - actionId: bot_message
            params:
              person: lucca
              messages:
                - text: ${outputs.user_answer.value.reply}
          - actionId: bot_message
            params:
              person: lucca
              messages:
                - text: Great reflection! Up next, we'll wrap up your Segment journey and talk
                    about next steps.
          - actionId: finish_step
      else:
        do:
          - actionId: bot_message
            params:
              person: lucca
              messages:
                - text: ${outputs.user_answer.value.reply}
